Parameters:
  Versioning:
    Default: 'Suspended'
    Type: String
    AllowedValues: [Enabled, Suspended]
  Department:
    Type: String
    Description: Department Name
    Default: 'IT'
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 's3-encrypted-file'
      AccessControl: Private
      VersioningConfiguration:
        Status: !Ref Versioning
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
